services:
    # nginx
    web:
        # in the future, create image and pull from there
        build:
            dockerfile: ./nginx/Dockerfile
        ports:
            - "80:80"

    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
            target: app

    # postgresql
    db:
        image: postgres:alpine3.19
        volumes:
            - postgresqldata:/var/lib/postgresql
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: workoutManager123
            POSTGRES_USER: supermanager
            POSTGRES_DB: workoutdb

    # redis

volumes:
    postgresqldata: