services:
    # nginx
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
            target: "${BUILD_TARGET:-app}"
        volumes:
            - ./app:/var/www/html
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        environment:
            POSTGRES_HOST: db
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            REDIS_HOST: cache
            REDIS_PORT: ${REDIS_PORT}
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
        extra_hosts:
            - host.docker.internal:host-gateway

    # postgresql
    db:
        image: postgres:alpine3.19
        volumes:
            - postgresqldata:/var/lib/postgresql
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: workoutManager123
            POSTGRES_USER: supermanager
            POSTGRES_DB: workoutdb

    # redis
    cache:
        image: redis:latest

volumes:
    postgresqldata: