services:
    # nginx
    web:
        image: hhiruko/nginx-php-fpm:1.0
        ports:
            - "80:80"

    # php
    app:
        image: hhiruko/php:1.0
        environment:
            POSTGRES_HOST: db
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            REDIS_HOST: cache
            REDIS_PORT: ${REDIS_PORT}
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
        extra_hosts:
            - host.docker.internal:host-gateway

    # postgresql
    db:
        image: postgres:alpine3.19
        volumes:
            - postgresqldata:/var/lib/postgresql
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    # redis
    cache:
        image: redis:latest

volumes:
    postgresqldata: